// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bikypcwedwypqycvcplq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpa3lwY3dlZHd5cHF5Y3ZjcGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzE3MTMsImV4cCI6MjA2ODAwNzcxM30.jXFtelPgeSrl3CKmdHfZsaQ3PR_vAZgY0OMa0Cv8ymo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});